# apiVersion: bigquery.gcp.upbound.io/v1beta1
# kind: Dataset
# metadata:
#   name: testdatasetmf
# spec:
#   forProvider:
#     location: US
#     access:
#     - role: OWNER
#       userByEmail: martin.mf65@gmail.com
# ---
# apiVersion: bigquery.gcp.upbound.io/v1beta2
# kind: Dataset
# metadata:
#   annotations:
#     crossplane.io/external-create-pending: "2025-01-06T20:25:55Z"
#     crossplane.io/external-create-succeeded: "2025-01-06T20:25:55Z"
#     crossplane.io/external-name: testdatasetmf
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"bigquery.gcp.upbound.io/v1beta1","kind":"Dataset","metadata":{"annotations":{},"name":"testdatasetmf"},"spec":{"forProvider":{"access":[{"role":"OWNER","userByEmail":"martin.mf65@gmail.com"}],"location":"US"}}}
#   creationTimestamp: "2025-01-06T20:25:55Z"
#   finalizers:
#   - finalizer.managedresource.crossplane.io
#   generation: 3
#   name: testdatasetmf
#   resourceVersion: "2016300"
#   uid: 8c85242b-e9c9-4c8b-a2a1-8c399ebc8e78
# spec:
#   deletionPolicy: Delete
#   forProvider:
#     access:
#     - role: OWNER
#       userByEmail: martin.mf65@gmail.com
#     location: US
#     maxTimeTravelHours: "168"
#     project: axial-life-395119
#   initProvider: {}
#   managementPolicies:
#   - '*'
#   providerConfigRef:
#     name: default
# status:
#   atProvider:
#     access:
#     - domain: ""
#       groupByEmail: ""
#       iamMember: ""
#       role: OWNER
#       specialGroup: ""
#       userByEmail: martin.mf65@gmail.com
#     creationTime: 1736195155986
#     defaultCollation: ""
#     defaultPartitionExpirationMs: 0
#     defaultTableExpirationMs: 0
#     deleteContentsOnDestroy: false
#     description: ""
#     etag: znFvmkKJNliSZuFZHcRD6g==
#     friendlyName: ""
#     id: projects/axial-life-395119/datasets/testdatasetmf
#     isCaseInsensitive: false
#     lastModifiedTime: 1736195155986
#     location: US
#     maxTimeTravelHours: "168"
#     project: axial-life-395119
#     selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/axial-life-395119/datasets/testdatasetmf
#     storageBillingModel: ""
#   conditions:
#   - lastTransitionTime: "2025-01-06T20:25:57Z"
#     reason: Available
#     status: "True"
#     type: Ready
#   - lastTransitionTime: "2025-01-06T20:25:55Z"
#     reason: ReconcileSuccess
#     status: "True"
#     type: Synced
#   - lastTransitionTime: "2025-01-06T20:25:56Z"
#     reason: Success
#     status: "True"
#     type: LastAsyncOperation
# ---
# apiVersion: bigquery.gcp.upbound.io/v1beta1
# kind: Dataset
# metadata:
#   name: testdataset
# spec:
#   forProvider:
#     location: US
# ---
# apiVersion: bigquery.gcp.upbound.io/v1beta2
# kind: Dataset
# metadata:
#   annotations:
#     crossplane.io/external-create-pending: "2025-01-06T19:59:34Z"
#     crossplane.io/external-create-succeeded: "2025-01-06T19:59:34Z"
#     crossplane.io/external-name: testdataset
#     kubectl.kubernetes.io/last-applied-configuration: |
#       {"apiVersion":"bigquery.gcp.upbound.io/v1beta1","kind":"Dataset","metadata":{"annotations":{},"name":"testdataset"},"spec":{"forProvider":{"location":"US"}}}
#   creationTimestamp: "2025-01-06T19:59:32Z"
#   finalizers:
#   - finalizer.managedresource.crossplane.io
#   generation: 3
#   name: testdataset
#   resourceVersion: "2012090"
#   uid: 26252153-32da-4570-8077-7c536e26ee7e
# spec:
#   deletionPolicy: Delete
#   forProvider:
#     access:
#     - role: OWNER
#       userByEmail: crossplane@axial-life-395119.iam.gserviceaccount.com
#     - role: OWNER
#       specialGroup: projectOwners
#     - role: READER
#       specialGroup: projectReaders
#     - role: WRITER
#       specialGroup: projectWriters
#     location: US
#     maxTimeTravelHours: "168"
#     project: axial-life-395119
#   initProvider: {}
#   managementPolicies:
#   - '*'
#   providerConfigRef:
#     name: default
# status:
  # atProvider:
  #   access:
  #   - domain: ""
  #     groupByEmail: ""
  #     iamMember: ""
  #     role: OWNER
  #     specialGroup: ""
  #     userByEmail: crossplane@axial-life-395119.iam.gserviceaccount.com
  #   - domain: ""
  #     groupByEmail: ""
  #     iamMember: ""
  #     role: OWNER
  #     specialGroup: projectOwners
  #     userByEmail: ""
  #   - domain: ""
  #     groupByEmail: ""
  #     iamMember: ""
  #     role: READER
  #     specialGroup: projectReaders
  #     userByEmail: ""
  #   - domain: ""
  #     groupByEmail: ""
  #     iamMember: ""
  #     role: WRITER
  #     specialGroup: projectWriters
  #     userByEmail: ""
  #   creationTime: 1736193574765
  #   defaultCollation: ""
  #   defaultPartitionExpirationMs: 0
  #   defaultTableExpirationMs: 0
  #   deleteContentsOnDestroy: false
  #   description: ""
  #   etag: p9XduyIEQ7zGJ5Ok6bEr2A==
  #   friendlyName: ""
  #   id: projects/axial-life-395119/datasets/testdataset
  #   isCaseInsensitive: false
  #   lastModifiedTime: 1736193574765
  #   location: US
  #   maxTimeTravelHours: "168"
  #   project: axial-life-395119
  #   selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/axial-life-395119/datasets/testdataset
  #   storageBillingModel: ""
  # conditions:
  # - lastTransitionTime: "2025-01-06T19:59:36Z"
  #   reason: Available
  #   status: "True"
  #   type: Ready
  # - lastTransitionTime: "2025-01-06T19:59:34Z"
  #   reason: ReconcileSuccess
  #   status: "True"
  #   type: Synced
  # - lastTransitionTime: "2025-01-06T19:59:35Z"
  #   reason: Success
  #   status: "True"
  #   type: LastAsyncOperation

apiVersion: bigquery.gcp.upbound.io/v1beta1
kind: Dataset
metadata:
  name: testdatasetreaderonly
spec:
  forProvider:
    location: US
    access:
    - role: READER
      userByEmail: martin.mf65@gmail.com
---
apiVersion: bigquery.gcp.upbound.io/v1beta2
kind: Dataset
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-01-06T20:27:58Z"
    crossplane.io/external-create-succeeded: "2025-01-06T20:27:58Z"
    crossplane.io/external-name: testdatasetreaderonly
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"bigquery.gcp.upbound.io/v1beta1","kind":"Dataset","metadata":{"annotations":{},"name":"testdatasetreaderonly"},"spec":{"forProvider":{"access":[{"role":"READER","userByEmail":"martin.mf65@gmail.com"}],"location":"US"}}}
  creationTimestamp: "2025-01-06T20:27:57Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: testdatasetreaderonly
  resourceVersion: "2016642"
  uid: 6d54c7d2-80d0-4de7-980d-d64ceb538603
spec:
  deletionPolicy: Delete
  forProvider:
    access:
    - role: READER
      userByEmail: martin.mf65@gmail.com
    location: US
    maxTimeTravelHours: "168"
    project: axial-life-395119
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    access:
    - domain: ""
      groupByEmail: ""
      iamMember: ""
      role: OWNER
      specialGroup: ""
      userByEmail: crossplane@axial-life-395119.iam.gserviceaccount.com
    - domain: ""
      groupByEmail: ""
      iamMember: ""
      role: READER
      specialGroup: ""
      userByEmail: martin.mf65@gmail.com
    creationTime: 1736195278999
    defaultCollation: ""
    defaultPartitionExpirationMs: 0
    defaultTableExpirationMs: 0
    deleteContentsOnDestroy: false
    description: ""
    etag: yULqoAQXVX5JqrxQ7Bwo5Q==
    friendlyName: ""
    id: projects/axial-life-395119/datasets/testdatasetreaderonly
    isCaseInsensitive: false
    lastModifiedTime: 1736195289123
    location: US
    maxTimeTravelHours: "168"
    project: axial-life-395119
    selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/axial-life-395119/datasets/testdatasetreaderonly
    storageBillingModel: ""
  conditions:
  - lastTransitionTime: "2025-01-06T20:28:00Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-01-06T20:28:09Z"
    message: 'update failed: async update failed: failed to update the resource: [{0
      Error updating Dataset "projects/axial-life-395119/datasets/testdatasetreaderonly":
      googleapi: Error 400: Cannot remove all owners from a dataset. "Dataset owner"
      means either the IAM role bigquery.dataOwner or BigQuery dataset OWNER role.
      Owners must be bound directly on the dataset itself without conditions: Inherited
      bindings (e.g., from the parent project) do not count., invalid  []}]'
    reason: ReconcileError
    status: "False"
    type: Synced
  - lastTransitionTime: "2025-01-06T20:28:09Z"
    message: 'async update failed: failed to update the resource: [{0 Error updating
      Dataset "projects/axial-life-395119/datasets/testdatasetreaderonly": googleapi:
      Error 400: Cannot remove all owners from a dataset. "Dataset owner" means either
      the IAM role bigquery.dataOwner or BigQuery dataset OWNER role. Owners must
      be bound directly on the dataset itself without conditions: Inherited bindings
      (e.g., from the parent project) do not count., invalid  []}]'
    reason: AsyncUpdateFailure
    status: "False"
    type: LastAsyncOperation