apiVersion: logging.gcp.upbound.io/v1beta1
kind: ProjectSink
metadata:
  name: my-sink
spec:
  forProvider:
    destination: pubsub.googleapis.com/projects/axial-life-395119/topics/topic
    # filter: resource.type = gce_instance AND severity >= WARNING
    # uniqueWriterIdentity: true
    project: axial-life-395119
---
apiVersion: logging.gcp.upbound.io/v1beta2
kind: ProjectSink
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-01-07T14:30:44Z"
    crossplane.io/external-create-succeeded: "2025-01-07T14:30:44Z"
    crossplane.io/external-name: my-sink
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"logging.gcp.upbound.io/v1beta1","kind":"ProjectSink","metadata":{"annotations":{},"name":"my-sink"},"spec":{"forProvider":{"destination":"pubsub.googleapis.com/projects/axial-life-395119/topics/topic","project":"axial-life-395119"}}}
  creationTimestamp: "2025-01-07T14:30:42Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: my-sink
  resourceVersion: "2167245"
  uid: cff04f33-6d02-4fc7-ac00-4813cc8d7f85
spec:
  deletionPolicy: Delete
  forProvider:
    destination: pubsub.googleapis.com/projects/axial-life-395119/topics/topic
    project: axial-life-395119
    uniqueWriterIdentity: true
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    description: ""
    destination: pubsub.googleapis.com/projects/axial-life-395119/topics/topic
    disabled: false
    filter: ""
    id: projects/axial-life-395119/sinks/my-sink
    project: axial-life-395119
    uniqueWriterIdentity: true
    writerIdentity: serviceAccount:service-376994270622@gcp-sa-logging.iam.gserviceaccount.com
  conditions:
  - lastTransitionTime: "2025-01-07T14:30:48Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-01-07T14:30:44Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-01-07T14:30:47Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation