apiVersion: storage.gcp.upbound.io/v1beta1
kind: BucketIAMMember
metadata:
  name: bucket-iam-member
spec:
  forProvider:
    bucketRef:
      name: gcp-provider-family-bucket-mf123
    member: allAuthenticatedUsers
    role: roles/storage.legacyObjectReader
---
apiVersion: storage.gcp.upbound.io/v1beta2
kind: BucketIAMMember
metadata:
  annotations:
    crossplane.io/external-create-pending: "2025-01-07T20:36:18Z"
    crossplane.io/external-create-succeeded: "2025-01-07T20:36:18Z"
    crossplane.io/external-name: b/gcp-provider-family-bucket-mf123/roles/storage.legacyObjectReader/allAuthenticatedUsers
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.gcp.upbound.io/v1beta1","kind":"BucketIAMMember","metadata":{"annotations":{},"name":"bucket-iam-member"},"spec":{"forProvider":{"bucketRef":{"name":"gcp-provider-family-bucket-mf123"},"member":"allAuthenticatedUsers","role":"roles/storage.legacyObjectReader"}}}
  creationTimestamp: "2025-01-07T20:36:17Z"
  finalizers:
  - finalizer.managedresource.crossplane.io
  generation: 3
  name: bucket-iam-member
  resourceVersion: "2218124"
  uid: 3f0381b8-726e-4c63-9986-253c490d7075
spec:
  deletionPolicy: Delete
  forProvider:
    bucket: gcp-provider-family-bucket-mf123
    bucketRef:
      name: gcp-provider-family-bucket-mf123
    member: allAuthenticatedUsers
    role: roles/storage.legacyObjectReader
  initProvider: {}
  managementPolicies:
  - '*'
  providerConfigRef:
    name: default
status:
  atProvider:
    bucket: b/gcp-provider-family-bucket-mf123
    etag: CAI=
    id: b/gcp-provider-family-bucket-mf123/roles/storage.legacyObjectReader/allAuthenticatedUsers
    member: allAuthenticatedUsers
    role: roles/storage.legacyObjectReader
  conditions:
  - lastTransitionTime: "2025-01-07T20:36:25Z"
    reason: Available
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-01-07T20:36:18Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-01-07T20:36:23Z"
    reason: Success
    status: "True"
    type: LastAsyncOperation